In [15]:

import pandas as pd
import numpy as np

In [16]:
df = pd.read_excel('Citas_Digital.xlsx')
df

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      object
 1   Fecha                                     88 non-null       datetime64[us]
 2   Nombre Cliente                            668 non-null      object
 3   Telefono                                  2 non-null        str
 4   Estatus de Lead                           654 non-null      object
 5   Potencial de compra                       614 non-null      object
 6   PDM                                       1048574 non-null  float64
 7   SDC                                       1048573 non-null  float64
 8   Venta                                     1048570 non-null  float64
 9   Asesor Asignado                           656 non-null      str
 10  ¿Por que no ha visitado la agencia?       493 non-null      str
 11  ¿Por que no hay solicitud de credito?     379 non-null      str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 13  ¿Por que no hubo proceso wow?             364 non-null      str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null      str
 15  Unnamed: 15                               16 non-null       str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 128.0+ MB

In [18]:
#Parte 1: Filtro por filas
filtro1 = df.iloc[0:673, :]
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    object
 1   Fecha                                     72 non-null     datetime64[us]
 2   Nombre Cliente                            652 non-null    object
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           638 non-null    object
 5   Potencial de compra                       599 non-null    object
 6   PDM                                       672 non-null    float64
 7   SDC                                       671 non-null    float64
 8   Venta                                     668 non-null    float64
 9   Asesor Asignado                           641 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 84.3+ KB

In [19]:
filtro1

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,Ignacio,2026-07-21,Carlos Balderrama,NaN,Activo,0.5,1.0,1.0,1.0,Mario Varela,NaN,NaN,NaN,NaN,NaN,NaN
669,Ignacio,2026-07-21,Andrés Netzahuatl,NaN,Activo,0.5,0.0,0.0,0.0,Mauricio,NaN,NaN,NaN,NaN,NaN,NaN
670,Ana,2026-07-22,Arat Israel,NaN,Activo,80&,1.0,1.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN,NaN
671,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Parte2: Filtro por columnas, aplicado sobre filtro1 (filas ya filtradas)
filtro2 = filtro1.iloc[:, [0, 1, 2, 4, 5, 6, 7, 8, 9]]
filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    object
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    object
 3   Estatus de Lead      638 non-null    object
 4   Potencial de compra  599 non-null    object
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(3), object(4), str(1)
memory usage: 47.4+ KB

In [21]:
filtro2

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
0,Saul,NaT,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy
1,Saul,NaT,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor
2,Saul,NaT,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan
3,Saul,NaT,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio
4,Saul,NaT,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio
...,...,...,...,...,...,...,...,...,...
668,Ignacio,2026-07-21,Carlos Balderrama,Activo,0.5,1.0,1.0,1.0,Mario Varela
669,Ignacio,2026-07-21,Andrés Netzahuatl,Activo,0.5,0.0,0.0,0.0,Mauricio
670,Ana,2026-07-22,Arat Israel,Activo,80&,1.0,1.0,0.0,Aurelio
671,Ana,2026-07-22,Maira Escalante,Activo,0.8,1.0,1.0,0.0,Pedro Antonio
672,Ignacio,2026-07-22,Zaira Macip,Activo,0.5,0.0,0.0,0.0,Aurelio

In [22]:
#Paso 3: "Potencial de Compra"
#Valores actuales de la columna antes de limpiarla
filtro2['Potencial de compra'].unique()

array([0.9, 0.4, 0.85, 0.2, 0.5, 0.8, 1, 0.6, 0.7, nan, 'Ventas ', 0.95,
       0.75, 0.05, '80%%', 0.65, "8'%", 0.3, '80&'], dtype=object)

In [23]:
#Nos aseguramos de que la columna esté en formato texto 
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].astype(str)

In [24]:
#Reemplazo de datos de la columna: cambiamos "Ventas " por "0"
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("Ventas ", "0", regex=False)

In [26]:
#Quitamos el símbolo de porcentaje
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("%", "", regex=False)

#Quitamos la comilla simple
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("'", "", regex=False)

#Quitamos el símbolo &
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("&", "", regex=False)

In [27]:
#Conversión final de tipo de dato de columna de tipo String a Float
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].astype(float)
filtro2['Potencial de compra'].dtype

dtype('float64')

In [28]:
filtro2['Potencial de compra'].unique()

array([9.0e-01, 4.0e-01, 8.5e-01, 2.0e-01, 5.0e-01, 8.0e-01, 1.0e+00,
       6.0e-01, 7.0e-01,     nan, 0.0e+00, 9.5e-01, 7.5e-01, 5.0e-02,
       8.0e+01, 6.5e-01, 8.0e+00, 3.0e-01])

In [29]:
#Pasao 4: Convertir archivo filtrado a CSV general
filtro2.to_csv("Citas_Digital_General.csv", index=False)
print("Archivo 'Citas_Digital_General.csv' generado con éxito")

Archivo 'Citas_Digital_General.csv' generado con éxito

In [30]:
#Paso 5: Dividir CSV por mes
#Leemos el archivo general para convertirlo en Dataframe
df_general = pd.read_csv("Citas_Digital_General.csv")
df_general['Fecha'] = pd.to_datetime(df_general['Fecha'])
df_general.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    str
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    str
 3   Estatus de Lead      638 non-null    str
 4   Potencial de compra  599 non-null    float64
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(4), str(4)
memory usage: 47.4 KB

In [32]:
#Diccionario para escribir el nombre del mes 
meses = {
    1: "Enero", 2: "Febrero", 3: "Marzo", 4: "Abril",
    5: "Mayo", 6: "Junio", 7: "Julio", 8: "Agosto",
    9: "Septiembre", 10: "Octubre", 11: "Noviembre", 12: "Diciembre"
}

#Generamos los 16 periodos: Abril 2025 |Julio 2026
periodos = pd.date_range(start="2025-04-01", end="2026-07-01", freq="MS")
periodos

DatetimeIndex(['2025-04-01', '2025-05-01', '2025-06-01', '2025-07-01',
               '2025-08-01', '2025-09-01', '2025-10-01', '2025-11-01',
               '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01',
               '2026-04-01', '2026-05-01', '2026-06-01', '2026-07-01'],
              dtype='datetime64[us]', freq='MS')

In [33]:
#Un archivo .csv por cada mes
for periodo in periodos:
    anio = periodo.year
    mes_num = periodo.month
    nombre_mes = meses[mes_num]

    filtro_mes = df_general[(df_general['Fecha'].dt.year == anio) & (df_general['Fecha'].dt.month == mes_num)]

    nombre_archivo = f"{nombre_mes}_{anio}.csv"
    filtro_mes.to_csv(nombre_archivo, index=False)
    print(f"{nombre_archivo}: {len(filtro_mes)} registros")

print("\n¡Los 16 archivos CSV mensuales se generaron con éxito!")

Abril_2025.csv: 0 registros
Mayo_2025.csv: 0 registros
Junio_2025.csv: 0 registros
Julio_2025.csv: 1 registros
Agosto_2025.csv: 0 registros
Septiembre_2025.csv: 0 registros
Octubre_2025.csv: 0 registros
Noviembre_2025.csv: 0 registros
Diciembre_2025.csv: 0 registros
Enero_2026.csv: 0 registros
Febrero_2026.csv: 0 registros
Marzo_2026.csv: 0 registros
Abril_2026.csv: 0 registros
Mayo_2026.csv: 0 registros
Junio_2026.csv: 44 registros
Julio_2026.csv: 27 registros

¡Los 16 archivos CSV mensuales se generaron con éxito!